branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

language: cpp

sudo: true

matrix:
  allow_failures:
    - os: osx

  include:
    - language: python
      sudo: false
      python: 2.7
      env: TASKS="clang-format"

      os: linux
      dist: trusty
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-6.0
          packages:
          - clang-format-6.0
      if: branch = master AND tag IS blank

    - compiler: gcc
      os: linux
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-4.9
      env:
        - TASKS="ctest gcc-4.9"
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
      if: branch = master AND tag IS blank

    - compiler: gcc
      os: linux
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-6
      env:
        - TASKS="ctest gcc-6.3"
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      if: branch = master AND tag IS blank

    - compiler: clang
      os: linux
      env: TASKS="ctest clang-3.9"
      if: branch = master AND tag IS blank

    - os: osx
      env: TASKS="Mac clang"
      if: branch = master AND tag IS blank

    - os: osx
      env: DEPLOY=TRUE
      if: tag IS present

install:
  - . ./scripts/travis/install.sh

script:
  - ./scripts/travis/build.sh

before_deploy:
  - ./scripts/travis/macpython-build-wheels.sh 3.5 3.6 3.7

# Currently we have todo the pypi upload in a script, as Travis's support is
# broken  :-(
deploy:
  provider: script
  script: ./scripts/travis/upload_pypi.sh
  skip_cleanup: true
  on:
    tags: true
