-
  version: 1.0.{build}
  image: Visual Studio 2017
  configuration:
  - Release
  clone_folder: C:/openchemistry/avogadrolibs
  init:
  - cmd:
  environment:
    PATH: '%PATH%;%QTDIR%\bin'
    matrix:
    - CMAKE_GENERATOR: '"Ninja"'
      QTDIR: C:\Qt\5.6\msvc2015_64
      platform: x64
    TWINE_USERNAME:
      secure: /dyl+sf2T84bLnO0uaEFSA==
    TWINE_PASSWORD:
      secure: S4lgG583FNPPUGhPBEwNkfeC5YHUFE/K9x3xujHO75I=

  build_script:
    - ps: >-
        if ($env:appveyor_repo_tag -eq 'false')
        {
          & scripts\appveyor\build.bat
        }

  install:
    - ps: >-
        if ($env:appveyor_repo_tag -eq 'true')
        {
          cd c:\openchemistry\avogadrolibs
          .\scripts\appveyor\build-wheels.ps1
        }

  deploy_script:
    - ps: >-
        if ($env:appveyor_repo_tag -eq 'true')
        {
          cd c:\openchemistry\avogadrolibs
          .\scripts\appveyor\upload-pypi.ps1
        }
