name: misspell-fixer

on: [workflow_dispatch]
jobs:
  spelling-check:
    name: Spelling Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5.0.0
    - name: misspell-fixer check for code and comments
      uses: sobolevn/misspell-fixer-action@master
      with:
        options: '-rsnuRVd avogadro/'
